### ISSUE TITLE
A @tag and comment end */ on the same line breaks the highlighting

### ISSUE THREAD

**Issue by gundas** [alin1popa/solidity-notepadplusplus-userdefined-highlight#3]
if  a comment contains a @tag and it ends on the same line, the highlighting gets broken,
For example:
```
contract test {
	/** @title - bla bla */
    uint256 badHighlighting;    
}
```

**Comment by alin1popa** [comment]
Thanks, but currently the standard Notepad++ user-defined languages do not support regular expressions. Without regex this is what happens whenever you try to embed a style delimited by EOL inside a normal style delimited by characters (such as comments).

The only fix is to just end the comment on the next line.
