### ISSUE TITLE
Faile to import xml file

### ISSUE THREAD

**Issue by L0N** [alin1popa/solidity-notepadplusplus-userdefined-highlight#6]
I downloaded the xml file and tried importing it. It failed.
I'm using Notepad++ v7.9.1 x64. Should I be using nppx32?

**Comment by alin1popa** [comment]
I just tested it with v7.9.1 x64 and it is working fine for me.
Please try to do it like this:
1. Check that the XML file downloaded correctly (e.g. open it in an editor, it should start with `<NotepadPlus>` and end with `</NotepadPlus>`
2. Close Notepad++
3. Copy the XML file into `%AppData%\Notepad++\userDefineLangs` (if you're using a portable version, this is going to be the `userDefineLangs` folder within your npp folder). If the `userDefineLangs` folder does not exist, just create it yourself.
4. Restart Notepad++. A "Solidity" entry should appear at the bottom of the list in the Language menu (and it should be automatically selected if you open a `.sol` file)
